"""create doctor_cards table

Revision ID: 91ffa5693e0a
Revises: 
Create Date: 2026-09-27 17:33:09.634613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91ffa5693e0a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('doctor_name', sa.String(length=100), nullable=False),
    sa.Column('clinic_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('street_address_1', sa.String(length=150), nullable=False),
    sa.Column('street_address_2', sa.String(length=150), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state_province', sa.String(length=50), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.CheckConstraint('char_length(trim(city)) >= 1', name='check_city_not_empty'),
    sa.CheckConstraint('char_length(trim(clinic_name)) >= 1', name='check_clinic_name_not_empty'),
    sa.CheckConstraint('char_length(trim(country)) >= 1', name='check_country_not_empty'),
    sa.CheckConstraint('char_length(trim(doctor_name)) >= 1', name='check_doctor_name_not_empty'),
    sa.CheckConstraint('char_length(trim(notes)) >= 1', name='check_notes_not_empty'),
    sa.CheckConstraint('char_length(trim(phone)) >= 1', name='check_phone_not_empty'),
    sa.CheckConstraint('char_length(trim(state_province)) >= 1', name='check_state_province_not_empty'),
    sa.CheckConstraint('char_length(trim(street_address_1)) >= 1', name='check_street_address_1_not_empty'),
    sa.CheckConstraint('char_length(trim(street_address_2)) >= 1', name='check_street_address_2_not_empty'),
    sa.CheckConstraint('char_length(trim(website)) >= 1', name='check_website_not_empty'),
    sa.CheckConstraint('char_length(trim(zip_code)) >= 1', name='check_zip_code_not_empty'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor_cards')
    # ### end Alembic commands ###
