"""rename columns to card_id and user_id

Revision ID: cffb96d3d47e
Revises: e7fdf60cd64a
Create Date: 2026-09-29 11:43:09.452844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cffb96d3d47e'
down_revision: Union[str, Sequence[str], None] = 'e7fdf60cd64a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_card', sa.Column('card_id', sa.Integer(), nullable=False))
    op.add_column('doctor_card', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.add_column('doctor_card', sa.Column('specialty', sa.String(length=100), nullable=False))
    op.drop_column('doctor_card', 'speciality')
    op.drop_column('doctor_card', 'owner_id')
    op.drop_column('doctor_card', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_card', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('doctor_card', sa.Column('owner_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('doctor_card', sa.Column('speciality', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('doctor_card', 'specialty')
    op.drop_column('doctor_card', 'user_id')
    op.drop_column('doctor_card', 'card_id')
    # ### end Alembic commands ###
