"""rename to doctor_card and add speciality

Revision ID: e7fdf60cd64a
Revises: 91ffa5693e0a
Create Date: 2026-09-29 10:33:51.397970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7fdf60cd64a'
down_revision: Union[str, Sequence[str], None] = '91ffa5693e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('doctor_name', sa.String(length=100), nullable=False),
    sa.Column('speciality', sa.String(length=100), nullable=False),
    sa.Column('clinic_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('street_address_1', sa.String(length=150), nullable=False),
    sa.Column('street_address_2', sa.String(length=150), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state_province', sa.String(length=50), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.CheckConstraint('char_length(trim(city)) >= 1', name='check_city_not_empty'),
    sa.CheckConstraint('char_length(trim(clinic_name)) >= 1', name='check_clinic_name_not_empty'),
    sa.CheckConstraint('char_length(trim(country)) >= 1', name='check_country_not_empty'),
    sa.CheckConstraint('char_length(trim(doctor_name)) >= 1', name='check_doctor_name_not_empty'),
    sa.CheckConstraint('char_length(trim(notes)) >= 1', name='check_notes_not_empty'),
    sa.CheckConstraint('char_length(trim(phone)) >= 1', name='check_phone_not_empty'),
    sa.CheckConstraint('char_length(trim(speciality)) >= 1', name='check_speciality_not_empty'),
    sa.CheckConstraint('char_length(trim(state_province)) >= 1', name='check_state_province_not_empty'),
    sa.CheckConstraint('char_length(trim(street_address_1)) >= 1', name='check_street_address_1_not_empty'),
    sa.CheckConstraint('char_length(trim(street_address_2)) >= 1', name='check_street_address_2_not_empty'),
    sa.CheckConstraint('char_length(trim(website)) >= 1', name='check_website_not_empty'),
    sa.CheckConstraint('char_length(trim(zip_code)) >= 1', name='check_zip_code_not_empty'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('doctor_cards')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_cards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('doctor_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('clinic_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('street_address_1', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('street_address_2', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('state_province', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('zip_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.CheckConstraint('char_length(TRIM(BOTH FROM city)) >= 1', name=op.f('check_city_not_empty')),
    sa.CheckConstraint('char_length(TRIM(BOTH FROM clinic_name)) >= 1', name=op.f('check_clinic_name_not_empty')),
    sa.CheckConstraint('char_length(TRIM(BOTH FROM country)) >= 1', name=op.f('check_country_not_empty')),
    sa.CheckConstraint('char_length(TRIM(BOTH FROM doctor_name)) >= 1', name=op.f('check_doctor_name_not_empty')),
    sa.CheckConstraint('char_length(TRIM(BOTH FROM notes)) >= 1', name=op.f('check_notes_not_empty')),
    sa.CheckConstraint('char_length(TRIM(BOTH FROM phone)) >= 1', name=op.f('check_phone_not_empty')),
    sa.CheckConstraint('char_length(TRIM(BOTH FROM state_province)) >= 1', name=op.f('check_state_province_not_empty')),
    sa.CheckConstraint('char_length(TRIM(BOTH FROM street_address_1)) >= 1', name=op.f('check_street_address_1_not_empty')),
    sa.CheckConstraint('char_length(TRIM(BOTH FROM street_address_2)) >= 1', name=op.f('check_street_address_2_not_empty')),
    sa.CheckConstraint('char_length(TRIM(BOTH FROM website)) >= 1', name=op.f('check_website_not_empty')),
    sa.CheckConstraint('char_length(TRIM(BOTH FROM zip_code)) >= 1', name=op.f('check_zip_code_not_empty')),
    sa.PrimaryKeyConstraint('id', name=op.f('doctor_cards_pkey'))
    )
    op.drop_table('doctor_card')
    # ### end Alembic commands ###
