"""make card_id autoincrement primary key

Revision ID: e9e003b20838
Revises: cffb96d3d47e
Create Date: 2026-10-07 17:06:45.933202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9e003b20838'
down_revision: Union[str, Sequence[str], None] = 'cffb96d3d47e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add auto-increment (IDENTITY) to card_id
    op.execute("ALTER TABLE doctor_card ALTER COLUMN card_id ADD GENERATED BY DEFAULT AS IDENTITY")
    # 2. Set card_id as the primary key
    op.create_primary_key("doctor_card_pkey", "doctor_card", ["card_id"])

def downgrade() -> None:
    op.drop_constraint("doctor_card_pkey", "doctor_card", type_="primary")
    op.execute("ALTER TABLE doctor_card ALTER COLUMN card_id DROP IDENTITY IF EXISTS")
